<!DOCTYPE html>
<html>
<head>
    <?= $this->meta->head($meta['head']) ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <div class="pt-4"></div>
                <h1>Profile Gallery Editor</h1>
                <div class="row">
                    <form method="POST" class="col-md-6">
                        <?= $form->csrfField('csrf') ?>
                        <div class="form-group">
                            <label for="inp-title">Title</label>
                            <input name="title" type="text" class="form-control" id="inp-title" value="<?= $this->req->getPost('title', $gallery->title) ?>">
                        </div>
                        <div class="form-group">
                            <label for="inp-image">Images</label>
                            <textarea name="images" class="form-control" id="inp-image" rows="3"><?= $this->req->getPost('images', $gallery->images) ?></textarea>
                        </div>
                        <hr>
                        <button class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <?= $this->meta->foot($meta['foot']) ?>
</body>
</html>